# Generated by Django 5.2.7 on 2025-10-23 18:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.CharField(db_index=True, help_text='Unique Telegram user ID', max_length=50, unique=True)),
                ('name', models.CharField(help_text='User display name (separate from first_name/last_name)', max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('kk', 'Kazakh')], default='en', help_text="User's preferred language (ISO 639-1 code)", max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Habit name', max_length=255, unique=True)),
                ('weight', models.IntegerField(default=10, help_text='Habit base weight for reward calculations (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(blank=True, help_text='Habit category (e.g., health, productivity)', max_length=100, null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether habit is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active', 'name'], name='habits_active_fff3e7_idx'), models.Index(fields=['category'], name='habits_categor_5fff7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reward name', max_length=255, unique=True)),
                ('weight', models.FloatField(default=1.0, help_text='Reward weight for selection probability')),
                ('type', models.CharField(choices=[('virtual', 'Virtual'), ('real', 'Real'), ('none', 'None')], default='virtual', help_text='Reward type', max_length=10)),
                ('pieces_required', models.IntegerField(default=1, help_text='Number of pieces needed (1 for instant rewards)', validators=[django.core.validators.MinValueValidator(1)])),
                ('piece_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value of each piece earned', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether reward is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type'], name='rewards_type_5c8906_idx'), models.Index(fields=['active'], name='rewards_active_7a5060_idx')],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When habit was completed')),
                ('got_reward', models.BooleanField(default=False, help_text='Whether a meaningful reward was given')),
                ('streak_count', models.IntegerField(default=1, help_text='Current streak for this habit')),
                ('habit_weight', models.IntegerField(help_text='Habit weight at time of completion (1-100)')),
                ('total_weight_applied', models.FloatField(help_text='Total calculated weight (habit × user × streak multiplier)')),
                ('last_completed_date', models.DateField(help_text='Date of completion (for streak tracking)')),
                ('habit', models.ForeignKey(help_text='Link to habit', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.habit')),
                ('user', models.ForeignKey(help_text='Link to user', on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(blank=True, help_text='Link to reward (if awarded)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_in_logs', to='core.reward')),
            ],
            options={
                'db_table': 'habit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RewardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_earned', models.IntegerField(default=0, help_text='Number of pieces earned so far')),
                ('claimed', models.BooleanField(default=False, help_text='Whether user has claimed this reward')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward', models.ForeignKey(help_text='Link to reward', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.reward')),
                ('user', models.ForeignKey(help_text='Link to user', on_delete=django.db.models.deletion.CASCADE, related_name='reward_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_progress',
                'ordering': ['reward__name'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='users_telegra_d76140_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'habit', '-timestamp'], name='habit_logs_user_id_6d498a_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', '-timestamp'], name='habit_logs_user_id_90c1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['last_completed_date'], name='habit_logs_last_co_a996f1_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['got_reward'], name='habit_logs_got_rew_359148_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardprogress',
            index=models.Index(fields=['user', 'reward'], name='reward_prog_user_id_bce439_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardprogress',
            index=models.Index(fields=['user'], name='reward_prog_user_id_fcfe0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rewardprogress',
            unique_together={('user', 'reward')},
        ),
    ]
