# Generated by Django 5.2.7 on 2025-11-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='max_daily_claims',
            field=models.IntegerField(blank=True, help_text='Maximum times this reward can be claimed per day (NULL or 0 = unlimited)', null=True),
        ),
    ]
