# Generated by Django 5.2.7 on 2025-11-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_reward_daily_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('event_type', models.CharField(choices=[('command', 'Command'), ('habit_completed', 'Habit Completed'), ('reward_selected', 'Reward Selected'), ('reward_claimed', 'Reward Claimed'), ('reward_reverted', 'Reward Reverted'), ('button_click', 'Button Click'), ('error', 'Error')], db_index=True, help_text='Type of event', max_length=20)),
                ('command', models.CharField(blank=True, help_text='Command name (e.g., /habit_done, /streaks)', max_length=100, null=True)),
                ('callback_data', models.CharField(blank=True, help_text='Button callback data from inline keyboards', max_length=255, null=True)),
                ('snapshot', models.JSONField(blank=True, help_text='State snapshot at time of event (JSON)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message and traceback (for ERROR events)', null=True)),
                ('habit', models.ForeignKey(blank=True, help_text='Related habit (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.habit')),
                ('habit_log', models.ForeignKey(blank=True, help_text='Related habit log entry (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.habitlog')),
                ('reward', models.ForeignKey(blank=True, help_text='Related reward (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.reward')),
                ('user', models.ForeignKey(help_text='User who triggered the event', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='bot_audit_l_user_id_dae223_idx'), models.Index(fields=['event_type', '-timestamp'], name='bot_audit_l_event_t_a910b7_idx')],
            },
        ),
    ]
