# Generated by Django 5.2.7 on 2025-11-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_bot_audit_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='habit',
            name='habits_active_fff3e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='reward',
            name='rewards_type_5c8906_idx',
        ),
        migrations.RemoveIndex(
            model_name='reward',
            name='rewards_active_7a5060_idx',
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this habit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this reward', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(help_text='Habit name', max_length=255),
        ),
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(help_text='Reward name', max_length=255),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'active', 'name'], name='habits_user_id_2aca56_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['user', 'type'], name='rewards_user_id_4de814_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['user', 'active'], name='rewards_user_id_cebe18_idx'),
        ),
    ]
