# Generated by Django 5.2.7 on 2025-11-23 13:44

from django.db import migrations


def assign_habits_and_rewards_to_first_user(apps, schema_editor):
    """
    Assign all existing habits and rewards to the first active user.

    This preserves existing data during the multi-user migration.
    If no active user exists, habits and rewards will remain unassigned (null).
    """
    User = apps.get_model('core', 'User')
    Habit = apps.get_model('core', 'Habit')
    Reward = apps.get_model('core', 'Reward')

    # Get the first active user
    first_user = User.objects.filter(is_active=True).order_by('date_joined').first()

    if first_user:
        # Assign all habits without a user to the first user
        habits_updated = Habit.objects.filter(user__isnull=True).update(user=first_user)
        print(f"Assigned {habits_updated} habits to user {first_user.telegram_id}")

        # Assign all rewards without a user to the first user
        rewards_updated = Reward.objects.filter(user__isnull=True).update(user=first_user)
        print(f"Assigned {rewards_updated} rewards to user {first_user.telegram_id}")
    else:
        print("WARNING: No active users found. Habits and rewards remain unassigned.")


def reverse_assignment(apps, schema_editor):
    """
    Reverse the assignment by setting user to null.

    This allows rolling back the migration if needed.
    """
    Habit = apps.get_model('core', 'Habit')
    Reward = apps.get_model('core', 'Reward')

    Habit.objects.all().update(user=None)
    Reward.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_user_to_habits_rewards'),
    ]

    operations = [
        migrations.RunPython(
            assign_habits_and_rewards_to_first_user,
            reverse_code=reverse_assignment
        ),
    ]
