# Generated by Django 5.2.7 on 2025-11-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assign_existing_to_first_user'),
    ]

    operations = [
        # Make user field non-nullable for Habit
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(
                help_text='User who owns this habit',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='habits',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Make user field non-nullable for Reward
        migrations.AlterField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(
                help_text='User who owns this reward',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rewards',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Add unique_together constraint for Habit
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('user', 'name')},
        ),
        # Add unique_together constraint for Reward
        migrations.AlterUniqueTogether(
            name='reward',
            unique_together={('user', 'name')},
        ),
    ]
