# Generated by Django 5.2.7 on 2025-11-23 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_make_user_required_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='allowed_skip_days',
            field=models.IntegerField(default=0, help_text='Number of consecutive days user can skip without breaking streak (0 for strict)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='habit',
            name='exempt_weekdays',
            field=models.JSONField(blank=True, default=list, help_text="List of weekday numbers (1=Mon, 7=Sun) that don't count against streak"),
        ),
    ]
