# Generated by Django 5.2.7 on 2025-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_habit_allowed_skip_days_habit_exempt_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='If True, reward can be claimed multiple times. If False, reward auto-deactivates after first claim.'),
        ),
        migrations.AlterField(
            model_name='botauditlog',
            name='event_type',
            field=models.CharField(choices=[('command', 'Command'), ('habit_completed', 'Habit Completed'), ('habit_reverted', 'Habit Reverted'), ('reward_selected', 'Reward Selected'), ('reward_claimed', 'Reward Claimed'), ('reward_reverted', 'Reward Reverted'), ('button_click', 'Button Click'), ('error', 'Error')], db_index=True, help_text='Type of event', max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('real', 'Real'), ('none', 'None')], default='real', help_text='Reward type', max_length=10),
        ),
    ]
