# Generated by Django 5.2.7 on 2026-01-01 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_is_recurring_to_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, help_text='SHA256 hash of the API key (never store plaintext)', max_length=64, unique=True)),
                ('name', models.CharField(help_text="User-friendly name (e.g., 'Fitness App', 'iOS Shortcut')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the key was created')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the key was last used', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the key is active (can be revoked)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='api_keys_user_id_6e7352_idx'), models.Index(fields=['key_hash'], name='api_keys_key_has_8f2f29_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit numeric code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the code was generated')),
                ('expires_at', models.DateTimeField(help_text='When the code expires (5 minutes from creation)')),
                ('used', models.BooleanField(default=False, help_text='Whether the code has been used')),
                ('device_info', models.CharField(blank=True, help_text='Device/browser info from the requesting app', max_length=255, null=True)),
                ('user', models.ForeignKey(help_text='User this code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code'], name='auth_codes_user_id_fd8e35_idx'), models.Index(fields=['expires_at'], name='auth_codes_expires_34e84a_idx')],
            },
        ),
    ]
