# Generated by Codex on 2025-10-23

from django.db import migrations


def deactivate_none_rewards(apps, schema_editor):
    Reward = apps.get_model("core", "Reward")
    Reward.objects.filter(type="none").update(active=False)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_authcode_lockout"),
    ]

    operations = [
        migrations.RunPython(deactivate_none_rewards, noop_reverse),
    ]
