# Generated by Django 5.2.7 on 2026-01-04 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_deactivate_none_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_reward_probability',
            field=models.FloatField(default=50.0, help_text='Probability of getting no reward during habit completion (0.01-99.99%)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99.99)]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('real', 'Real')], default='real', help_text='Reward type', max_length=10),
        ),
    ]
