# Generated by Django 5.2.7 on 2026-01-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_no_reward_probability_to_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reward',
            name='rewards_user_id_4de814_idx',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='type',
        ),
    ]
