# Generated by Django 5.2.7 on 2026-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_reward_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram message ID of the code message (for deletion)', null=True),
        ),
    ]
