# Generated by Django 5.2.7 on 2026-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_authcode_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_bot_message_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the last bot message (for editing from REST API)', null=True),
        ),
    ]
