# Generated by Django 5.2.7 on 2026-02-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_user_last_bot_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's IANA timezone (e.g. Asia/Almaty, Europe/Moscow)", max_length=50),
        ),
    ]
