# Generated by Django 5.2.7 on 2026-02-21 13:31

import src.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_timezone_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's IANA timezone (e.g. Asia/Almaty, Europe/Moscow)", max_length=50, validators=[src.core.models.validate_iana_timezone]),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'last_completed_date'], name='habit_logs_user_id_b51000_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'habit', 'last_completed_date'], name='habit_logs_user_id_7341c3_idx'),
        ),
    ]
