# Generated by Django 5.2.7 on 2026-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_habitlog_date_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rewardprogress',
            index=models.Index(fields=['user', 'claimed'], name='reward_prog_user_id_e67991_idx'),
        ),
    ]
