# Generated by Django 5.2.7 on 2026-02-26 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0018_add_reward_progress_claimed_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLoginRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Random token for polling status', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied')], default='pending', help_text='Current status of the login request', max_length=10)),
                ('device_info', models.CharField(blank=True, help_text='Browser/device info from the requesting client', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was created')),
                ('expires_at', models.DateTimeField(help_text='When the request expires (5 minutes from creation)')),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Telegram message ID of the Confirm/Deny message', null=True)),
            ],
            options={
                'db_table': 'web_login_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, help_text='Telegram @username (lowercase, without @)', max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_username'], name='users_telegra_5ecf28_idx'),
        ),
        migrations.AddField(
            model_name='webloginrequest',
            name='user',
            field=models.ForeignKey(help_text='User this login request belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='web_login_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['token'], name='web_login_r_token_cb65d0_idx'),
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['user', 'status'], name='web_login_r_user_id_d1bfff_idx'),
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['expires_at'], name='web_login_r_expires_336ea2_idx'),
        ),
    ]
