# Generated by Django 5.2.7 on 2026-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_webloginrequest_user_telegram_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, help_text='Telegram @username (lowercase, without @)', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webloginrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied'), ('used', 'Used')], default='pending', help_text='Current status of the login request', max_length=10),
        ),
    ]
