# Generated by Django 5.2.7 on 2026-02-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_telegram_username_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['token', 'status'], name='web_login_r_token_status_idx'),
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['created_at'], name='web_login_r_created_at_idx'),
        ),
    ]
