# Generated by Django 5.2.7 on 2026-02-27 05:00

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Remove the created_at index if it exists (may be missing in some DBs)."""
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute(
            "DROP INDEX IF EXISTS web_login_r_created_at_idx"
        )
    else:
        try:
            schema_editor.execute(
                "DROP INDEX IF EXISTS web_login_r_created_at_idx"
            )
        except Exception:
            pass  # Index doesn't exist, nothing to drop


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0021_add_webloginrequest_token_status_index'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='webloginrequest',
                    name='web_login_r_created_at_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(remove_index_if_exists, migrations.RunPython.noop),
            ],
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='wlr_user_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('telegram_username__isnull', True), ('telegram_username__regex', '^[a-z0-9_]{3,32}$'), _connector='OR'), name='user_telegram_username_format'),
        ),
    ]
