# Generated by Django 5.2.7 on 2026-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_username_constraint_and_login_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(
                fields=['token', 'status', 'expires_at'],
                name='wlr_status_check_idx',
            ),
        ),
    ]
