# Generated by Django 5.2.7 on 2026-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_wlr_status_check_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webloginrequest',
            name='wlr_user_status_created_idx',
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='wlr_user_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['user', 'expires_at'], name='wlr_user_expires_idx'),
        ),
    ]
