# Generated by Django 5.2.7 on 2026-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_update_web_login_request_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTokenIpBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Login token (matches WebLoginRequest.token)', max_length=64, unique=True)),
                ('ip_address', models.CharField(help_text='IPv4 or IPv6 address that created the token', max_length=45)),
                ('expires_at', models.DateTimeField(help_text='When this binding expires (same as the login request)')),
            ],
            options={
                'db_table': 'login_token_ip_bindings',
            },
        ),
        migrations.AddIndex(
            model_name='webloginrequest',
            index=models.Index(fields=['user'], name='wlr_user_idx'),
        ),
        migrations.AddIndex(
            model_name='logintokenipbinding',
            index=models.Index(fields=['expires_at'], name='ltib_expires_idx'),
        ),
    ]
