# Generated by Django 5.2.7 on 2026-03-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_times_claimed_to_rewardprogress'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rewardprogress',
            index=models.Index(fields=['user', 'times_claimed'], name='core_rewardprogress_user_times_claimed_idx'),
        ),
    ]
