# Generated by Django 5.2.7 on 2026-03-02 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_times_claimed_to_rewardprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='weight',
            field=models.IntegerField(default=0, help_text='Habit weight for reward probability bonus (0-30, each point = -1% no-reward, min floor applied)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit_weight',
            field=models.IntegerField(help_text='Habit weight at time of completion (0-30)'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='total_weight_applied',
            field=models.FloatField(help_text='Effective no-reward probability % applied during reward selection (pre-0026 records contain legacy multiplier values)'),
        ),
        migrations.AddIndex(
            model_name='rewardprogress',
            index=models.Index(fields=['user', 'times_claimed'], name='reward_prog_user_id_d9b7c0_idx'),
        ),
    ]
