# Generated by Django 5.2.7 on 2026-03-02 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_index_user_times_claimed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rewardprogress',
            new_name='reward_prog_user_id_d9b7c0_idx',
            old_name='core_rewardprogress_user_times_claimed_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark_emerald', 'Dark Emerald'), ('light_clean', 'Light Clean'), ('neon_cyberpunk', 'Neon Cyberpunk'), ('warm_earth', 'Warm Earth'), ('ocean_gradient', 'Ocean Gradient'), ('ios_glass', 'iOS Glass'), ('minimal_ink', 'Minimal Ink')], default='dark_emerald', help_text="User's selected UI theme", max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='weight',
            field=models.IntegerField(default=0, help_text='Habit weight for reward probability bonus (0-30, each point = -1% no-reward, min floor applied)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit_weight',
            field=models.IntegerField(help_text='Habit weight at time of completion (0-30)'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='total_weight_applied',
            field=models.FloatField(help_text='Effective no-reward probability % applied during reward selection (pre-0026 records contain legacy multiplier values)'),
        ),
    ]
